### ISSUE TITLE
Add config file that generates the final executable

### ISSUE THREAD

**Issue by F0xedb** [ODEX-TOS/tos-installer-backend#3]
Currently the backend has no API (except beeing used as a python module)
However a "frontend" should not be written in python. So I propose the following.
The api should be parsing a config file.
This could be a `config.json, config.toml or config.yaml`

An example of a config file would be the following
```yaml
models:
    - disks:
        - disk:
                device: "/dev/sda"
                size: "499G"
                gpt: true
                partitions:
                      - partition:
                              name: "efi"
                              mount: "/boot/efi"
                              filesystem: "fat32"
                              start: "1MiB"
                              end: "200MiB"
                       - partition:
                              name: "root"
                              mount: "/boot/efi"
                              filesystem: "ext4"
                              start: "200MiB"
                              end: "100%"
    - chroots:
                - chroot:
                         name: "root"
                - chroot:
                         name: "alpha"
    - users:
                - user:
                          name:"alpha"
                          password:"123"
    - bootloader:
                device: "/dev/sda"
    - system:
                local: "en_US.UTF-8"
                keymap: "be-latin1"
                hostname: "tos"
                password: "123"
    - packages:
                - package:
                         name: "userpackages"
                         packagefile: "packages.txt" # either from a file
                         package: # or a list in this format
                                - a
                                - b
execution:
       - partitiontable : "/dev/sda" # build a partition table
       - format : "/dev/sda1" # format a partitoin
       - format : "/dev/sda2"
       - mount : "/dev/sda" # mount all partitions from this drive
       - bootstrap # bootstrap the system
       - fstab # generate fstab based on mounted partitions
       - chroot: "root" # execute the next steps in the chrooted environment
                - systemsetup
                - createUser: "alpha"
                - bootloader
       - chroot: "alpha"   
                - packages: "userpackages"
```
This is an example yaml file that does 2 things.
It contains a model of what you wish to build eg the disk, partitions, encryption, users etc
It also contains the execution step. This is a step that tells in which sequence "something" must happen. It has some "functions" that operate on the models. The file above is an example config file for building a basic system

At the time of writing the above yaml file will generate the following

```bash
# build partition table
parted --script '/dev/sda' mklabel msdos
parted --script '/dev/sda' mkpart primary 1MiB 200MiB
parted --script '/dev/sda' name 0 efi
parted --script '/dev/sda' mkpart primary 200MiB 800MiB
parted --script '/dev/sda' set 1 boot on
parted --script '/dev/sda' name 1 boot
parted --script '/dev/sda' mkpart primary 800MiB 8GiB
parted --script '/dev/sda' name 2 swap
parted --script '/dev/sda' mkpart primary 8GiB 100%
parted --script '/dev/sda' set 3 lvm on
parted --script '/dev/sda' name 3 root


# format the partitions
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
mkfs.ext4 /dev/sda3
modprobe dm-crypt
modprobe dm-mod
cryptsetup luksFormat -v -s 512 -h sha512 /dev/sda4
cryptsetup open /dev/sda4 luks_lvm
pvcreate /dev/mapper/luks_lvm
vgcreate /dev/mapper/luks_lvm
lvcreate -n root -L 200G tos
lvcreate -n home -L 200G tos
mkfs.ext4 -L root /dev/mapper/tos-root
mkfs.ext4 -L home /dev/mapper/tos-home


# mount the partitions
mount /dev/mapper/tos-home /mnt/
mount /dev/mapper/tos-root /mnt/home
mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi
mkdir -p /mnt/boot
mount /dev/sda2 /mnt/boot
swapon /dev/sda3
swapon -a
swapon -s


# bootstrapping base system
pacstrap --noconfirm /mnt base base-devel efibootmgr vim dialog xterm grub 


# generating fstab
genfstab -U -p /mnt > /mnt/etc/fstab


# chrooting as root
arch-chroot -u root /mnt <<<EOF
timedatectl set-ntp true
location-generator
hwclock --systohc
sed -i 's:^#.*en_US.UTF-8:en_US.UTF-8' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf
echo KEYMAP='be-latin1' > /etc/vconsole.conf
echo 'tos' > /etc/hostname
echo -e '127.0.0.1   localhost
::1      localhost
127.0.1.1    tos.localdomain  tos' > /etc/hosts
passwd < 123
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
printf '[tos]
SigLevel = Optional TrustAll
Server = https://repo.pbfp.xyz
' >> /etc/pacman.conf
pacman -Syu --noconfirm git sudo base-devel zsh 
useradd -m -p paN8aiEIonqJE -g users -G audio lp optical storage video wheel games power -s /bin/bash alpha
grub-install --root-directory=/boot /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

EOF


# chrooting as user
arch-chroot -u alpha /mnt <<<EOF
pacman -Syu --noconfirm a b c d 

EOF
```
