### ISSUE TITLE
Add yaml file for parsing config.

### ISSUE THREAD

**Issue by F0xedb** [ODEX-TOS/tos-installer-backend#6]
The title says it all. You should be able to specify all the configurations from a configfile. The configfile is then parsed into a config object that is sharable by all models.
example section of a config file

```yaml
INSTALLCOMMAND: "pacman -Syu --noconfirm"
WIFI_CONNECT_COMMAND_WITH_PASSWORD: "nmcli device wifi connect '{}' password '{}'"
DEFAULT_SHELL: "/bin/bash"
GROUPS:
 - audio
 - lp
 - optical
 - storage
 - video 
 - wheel
 - games
 - power
```
