### ISSUE TITLE
Specify the optional partition number

### ISSUE THREAD

**Issue by F0xedb** [ODEX-TOS/tos-installer-backend#8]
When you want to install an OS at the moment you need to specify **ALL** partitions. Even the partitions that you do not need for this specific OS. The reason you need to specify all partitions is because the generator calculates the partition number based on the partitions on a disk.I propose a partitionoffset on the partition object. This offset is then the partition number. Something like this

```yaml
partition:
 # normal parameters
 offset: 5 # should generate /dev/sda5 if the device is /dev/sda or /dev/nvme0n1p5 if the device is /dev/nvme0n1
```

With this option you need to generate a partitiontable that doesn't get created from scratch.
I propose that you add the following to the disk object as well

```yaml
disk:
 # normal parameters
 newTable: false # don't create a new partition table but keep the existing. All partition that  are specified will then be added to the exisiting partition table
```

With these new options you can build/format and mount your drives even if an exisiting partitiontable (that by default is not supported) exists

We should also probably add a resize command that resizes a exisiting partition

That would propably be a new issue but I will drop the information here anyway.

A resize partition should at least contain something like this
```yaml
partition:
 resize: true
 offset: 5
 size: "100GB"
```

It would than generate something like this
```bash
parted --script /dev/sda resizepart 5 100GB
```

The new size could shrink or enlarge that exisiting partition.
